pipeline {
    agent any
    environment {
        CONFIG_FILE = 'bankos-dr/configuration/common/transfer-family/configuration.json'
    }
    parameters {
        password(name: 'AWS_ACCESS_KEY_ID', defaultValue: '', description: 'AWS_ACCESS_KEY_ID')
        password(name: 'AWS_SECRET_ACCESS_KEY', defaultValue: '', description: 'AWS_SECRET_ACCESS_KEY')
        password(name: 'AWS_SESSION_TOKEN', defaultValue: '', description: 'AWS_SESSION_TOKEN')

        booleanParam(name: 'DRY_RUN', defaultValue: false, description: 'Run the script in dry-run mode')
    }
    stages {
        stage('Install Node.js and Packages') {
            steps {
                sh '''
                cd bankos-dr
                npm install
                '''
            }
        }
        stage('Process Configuration') {
            steps {
                script {
                    env.AWS_ACCESS_KEY_ID = params.AWS_ACCESS_KEY_ID
                    env.AWS_SECRET_ACCESS_KEY = params.AWS_SECRET_ACCESS_KEY
                    env.AWS_SESSION_TOKEN = params.AWS_SESSION_TOKEN

                    def command = "node bankos-dr/services/transfer-family-user/main.js -f ${CONFIG_FILE}"

                    if (params.DRY_RUN) {
                        echo "DRY RUN enabled. Would run: ${command}"
                    } else {
                        echo "Running: ${command}"
                        sh command
                    }
                }
            }
        }
    }
}
