def  failoverLambdaFunctionArray= ['test-function-waqar']
def  activeLambdaFunctionArray= ['dani-test-function']

pipeline {
    agent any
    environment {
        CONFIG_FILE = './lambda/configuration.json'
    }
    parameters {
        choice(name: 'SWITCHING_TO', choices: ['ACTIVE', 'FAILOVER'], description: 'Select the environment')
        choice(name: 'CLIENT_NAME', choices: ['FED', 'RTP', 'FED-ACH'], description: 'Select the CLIENT_NAME')
        password(name: 'AWS_ACCESS_KEY_ID', defaultValue: '', description: 'AWS_ACCESS_KEY_ID')
        password(name: 'AWS_SECRET_ACCESS_KEY', defaultValue: '', description: 'AWS_SECRET_ACCESS_KEY')
        password(name: 'AWS_SESSION_TOKEN', defaultValue: '', description: 'AWS_SESSION_TOKEN')

        booleanParam(name: 'DRY_RUN', defaultValue: false, description: 'Check this to run the pipeline in dry run mode')
        booleanParam(name: 'PROCESS_CURRENT_ENV', defaultValue: false, description: 'Check this to process current environment')

    }

    stages {
        stage('Install Node.js Packages') {
            steps {
                sh '''
                cd bankos-dr
                npm install
                '''
            }
        }

        stage('Load and Process Configuration') {
            steps {
                script {
                    env.AWS_ACCESS_KEY_ID = params.AWS_ACCESS_KEY_ID
                    env.AWS_SECRET_ACCESS_KEY = params.AWS_SECRET_ACCESS_KEY
                    env.AWS_SESSION_TOKEN = params.AWS_SESSION_TOKEN
                    env.SWITCHING_TO = params.SWITCHING_TO

                    // Split the keywords string into an array
                    def command = 'node bankos-dr/services/lambda/main.js'

                    env.CLIENT_NAME = params.CLIENT_NAME

                    if (params.DRY_RUN) {
                        command += ' -dr'
                    }
                    if (params.PROCESS_CURRENT_ENV) {
                        command += ' -pce'
                    }
                    sh command
                }
            }
        }
    }
}
